name: Moar
main: net.serenity.moar.Moar
version: 0.4
author: MonsieurApple
commands:
  m:
      description: Completes the stack of whatever you're holding.
      usage: /<command> <#>
  moar:
      description: Completes the stack of whatever you're holding.
      usage: /<command> <#>